#
#dnf install java-21
#jenkin repo 
#yum instatll jenkins 
#start the jenkins 
#status 
#enable at boot
#systemctl enable jenkins

---
  - name: jenkins-configuration
    hosts: webservers 
    become: true
    

    tasks:
      - name: install java
        ansible.builtin.dnf: 
          name: java-21-amazon-corretto
          state: present

      - name: add jenkins repo 
        ansible.builtin.get_url :
          url: https://pkg.jenkins.io/rpm-stable/jenkins.repo
          dest: /etc/yum.repos.d/jenkins.repo
          mode: 0644

      - name: install jenkins
        ansible.builtin.dnf:
          name: jenkins
          state: present

      - name: start the jenkins 
        ansible.builtin.service:
          name: jenkins 
          state: started

      - name: enable jenkins 
        ansible.builtin.service:
          name: jenkins
          enabled: true

      - name: check jenkins status 
        ansible.builtin.command: service jenkins status
        register: jenkins_status

      - name: verify register output
        ansible.builtin.debug:
          var: jenkins_status
